objects/Account.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>States__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hyderabad</fullName>
                </value>
                <value>
                    <fullName>Warangal</fullName>
                </value>
                <value>
                    <fullName>Nalgonda</fullName>
                </value>
                <value>
                    <fullName>Guntur</fullName>
                </value>
                <value>
                    <fullName>Krishna</fullName>
                </value>
                <value>
                    <fullName>Prakasam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AndhraPradesh</fullName>
                </value>
                <value>
                    <fullName>Telangana</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Account_Handler.cls
/**
 * @description if State is not null so you have to select district field as well.
 */
public without sharing class Account_Handler {
     /**
     * @description Method to insert or update records
     * @param accounts list of accounts
     */
    public static void updateOrInsertRecords(List<Account> accounts){
        for(Account a:accounts){
            if(a.States__c != null){
                if(a.District__c==null)
                a.District__c.addError('Select District Value');
            }
        }
    }
}