objects/Contact.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>State__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Guntur</fullName>
                </value>
                <value>
                    <fullName>Krishna</fullName>
                </value>
                <value>
                    <fullName>Nalgonda</fullName>
                </value>
                <value>
                    <fullName>Adilabad</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>Telangana</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Contact_Handler.cls
/**
 * @description if State is not null so you have to select district field as well.
 */
public without sharing class Contact_Handler {
     /**
     * @description Method to insert or update records
     * @param contacts list of contacts
     */
    public static void updateOrInsertRecords(List<Contact> contacts){
        for(Contact a:contacts){
            if(a.State__c != null){
                if(a.District__c==null){
                a.District__c.addError('Select District Value');
                }
            }
        }
    }
}