objects/Discount_Rules__mdt.object
<CustomObject>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <label>Discount Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sports</fullName>
                    <default>true</default>
                    <label>Sports</label>
                </value>
                <value>
                    <fullName>Cloths</fullName>
                </value>
                <value>
                    <fullName>Home Furniture</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Validity__c</fullName>
        <label>Product Validity</label>
        <type>Date</type>
    </fields>
    <label>Discount Rules</label>
    <pluralLabel>Discount Rules</pluralLabel>
</CustomObject>

classes/Opportunity_Metadata_Query.cls
/**
 * @description pass this list to OpportunityDiscount class method
 */
public without sharing class Opportunity_Metadata_Query {
    /**
     * @description method as queryRecords
     * @return List<Discount_Rules__mdt>
     */
    public static List<Discount_Rules__mdt> queryRecords(){
        // Make sure we can update the database before even trying
        if (Schema.sObjectType.Discount_Rules__mdt.isAccessible()) {
            return [SELECT id,Product_Validity__c,Discount_Percentage__c,Product_Category__c FROM Discount_Rules__mdt];
        }else{
            return new List<Discount_Rules__mdt>();
        }
    }
}