objects/Discount_Rule__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Discount Rule</label>
</CustomObject>

objects/Discount_Rules__mdt.object
<CustomObject>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <label>Discount Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sports</fullName>
                    <default>true</default>
                    <label>Sports</label>
                </value>
                <value>
                    <fullName>Cloths</fullName>
                </value>
                <value>
                    <fullName>Home Furniture</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Validity__c</fullName>
        <label>Product Validity</label>
        <type>Date</type>
    </fields>
    <label>Discount Rules</label>
    <pluralLabel>Discount Rules</pluralLabel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Home Furniture</fullName>
                </value>
                <value>
                    <fullName>Cloths</fullName>
                </value>
                <value>
                    <fullName>Sports</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ProductDiscountTest.cls
@isTest
public class ProductDiscountTest {
	@isTest
    public static void testCallMe() {
        
        Opportunity o=new Opportunity();
        o.Name='Silver';
        o.CloseDate=Date.today()+10;
        o.StageName='Prospecting';
        o.Product_Category__c=Label.Product_Category_Label;
        o.Discount__c=30;
        insert o;
        Discount_Rules__mdt serviceMetadat =[SELECT id,Product_Validity__c,
                                                    Discount_Percentage__c FROM Discount_Rules__mdt
                                                    WHERE Product_Category__c=:o.Product_Category__c AND Product_Validity__c >=TODAY limit 1];
        Profile p=[select id,name from Profile where name='Standard User'];
        Discount_Rule__c instance = Discount_Rule__c.getInstance(p.Id);
        
        if(serviceMetadat!=null && instance.Discount__c!=null)
        {
             System.assertEquals(o.Discount__c,80);
        }
        else if(serviceMetadat!=null)
        {
             System.assertEquals(o.Discount__c,30);
        }
        
        o.CloseDate=Date.today()+11;
        update o;
        if(serviceMetadat!=null && instance.Discount__c!=null)
        {
             System.assertEquals(o.Discount__c,80);
        }
        else if(serviceMetadat!=null)
        {
             System.assertEquals(o.Discount__c,30);
        }
    }
}



       /* 
           // Create metadata instance
        Metadata.CustomMetadata mData = new Metadata.CustomMetadata();
        mData.fullName = 'Salesforce_Metadata_Rule';
        mData.Label = 'Salesforce_Rule';

        // Create metadata value instance
        Metadata.CustomMetadataValue instance = new Metadata.CustomMetadataValue();
        instance.field = 'Rule_Name__c';
        instance.value = 'New Value';
        
        instance.field = 'Product_Validity__c';
        instance.value = Date.today()+1;
        
        instance.field = 'Discount_Percentage__c';
        instance.value = 40;
        
        instance.field = 'Product_Category__c';
        instance.value = 'Cloth';

        // Add values to the record
        mData.values.add(instance);

        // Create deploy container
        Metadata.DeployContainer container = new Metadata.DeployContainer();
        container.addMetadata(mData);
	*/