objects/Discount_Rule__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Discount Rule</label>
</CustomObject>

objects/Discount_Rules__mdt.object
<CustomObject>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <label>Discount Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sports</fullName>
                    <default>true</default>
                    <label>Sports</label>
                </value>
                <value>
                    <fullName>Cloths</fullName>
                </value>
                <value>
                    <fullName>Home Furniture</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Discount Rules</label>
    <pluralLabel>Discount Rules</pluralLabel>
</CustomObject>

classes/UtilityClassTest.cls
@isTest
public class UtilityClassTest {
  @isTest
    static void testDiscountRulesMdtStub() {
        // Instantiate the StubProviderImpl class
        UtilityClass stubProvider = new UtilityClass();

        // Simulate a call to handleMethodCall for Discount_Rules__mdt
        Discount_Rules__mdt simulatedRecord = (Discount_Rules__mdt)stubProvider.handleMethodCall(
            new Discount_Rules__mdt(),
            '',
            Discount_Rules__mdt.class,
            new List<Type>{ Discount_Rules__mdt.class },
            new List<String>(),
            new List<Object>()
        );

        // Verify that the simulated Discount_Rules__mdt record has the expected values
        System.assertEquals('Cloths', simulatedRecord.Product_Category__c, 'Product Category should be Cloths');
        System.assertEquals(20.0, simulatedRecord.Discount_Percentage__c, 'Discount Percentage should be 20.0');
    }

    @isTest
    static void testDiscountRuleCStub() {
        // Instantiate the StubProviderImpl class
        UtilityClass stubProvider = new UtilityClass();

        // Simulate a call to handleMethodCall for Discount_Rule__c
        Discount_Rule__c simulatedRecord = (Discount_Rule__c)stubProvider.handleMethodCall(
            new Discount_Rule__c(),
            '',
            Discount_Rule__c.class,
            new List<Type>{ Discount_Rule__c.class },
            new List<String>(),
            new List<Object>()
        );

        // Verify that the simulated Discount_Rule__c record has the expected values
        System.assertEquals(20.0, simulatedRecord.Discount__c, 'Discount should be 20.0');
    }
}