objects/Discount_Rule__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Discount Rule</label>
</CustomObject>

objects/Discount_Rules__mdt.object
<CustomObject>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <label>Discount Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sports</fullName>
                    <default>true</default>
                    <label>Sports</label>
                </value>
                <value>
                    <fullName>Cloths</fullName>
                </value>
                <value>
                    <fullName>Home Furniture</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Discount Rules</label>
    <pluralLabel>Discount Rules</pluralLabel>
</CustomObject>

classes/UtilityClass.cls
public class UtilityClass implements StubProvider {
   public Object handleMethodCall(Object stubbedObject, String stubbedMethodName,
                                   Type returnType, List<Type> listOfReturnTypes,
                                   List<String> listOfNamesOfParam, List<Object> listOfParamValues) {
        if (stubbedObject instanceof Discount_Rules__mdt) {
            // Simulate Discount_Rules__mdt record
            return new Discount_Rules__mdt(Product_Category__c = 'Cloths', Discount_Percentage__c = 20.0);
        } else if (stubbedObject instanceof Discount_Rule__c) {
            // Simulate Discount_Rule__c record
            return new Discount_Rule__c(Discount__c = 20.0);
        }
        return null;
    }
}